dbt_project:
  outputs:
    dev:

      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', 5432) }}"
      user: admin
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'password') }}"
      dbname: article_db
      schema: dbt_schema
      threads: 1
      keepalives_idle: 0 # Default: 0 (no keepalives)
      connect_timeout: 10 # Default: 10
      retries: 0 # Default: 0

  target: dev
