services:
  qdrant:
    container_name: qdrant_new
    build:
      context: ./qdrant
      dockerfile: Dockerfile
    image: qdrant-image
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/data
    networks:
      - elt_bridge_network

volumes:
  qdrant_data:

networks:
    elt_bridge_network:
      driver: bridge
