services:
  spark-master:
    container_name: spark-master-con
    build:
      context: ./spark
      dockerfile: Dockerfile
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark/scripts/:/opt/spark/scripts
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'
    networks:
      - elt_bridge_network


  spark-history-server:
    container_name: spark-history-con
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    networks:
      - elt_bridge_network

  spark-worker:
#    container_name: da-spark-worker
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark/scripts/:/opt/spark/scripts
      - spark-logs:/opt/spark/spark-events
    networks:
      - elt_bridge_network

volumes:
  spark-logs:
networks:
    elt_bridge_network:
      driver: bridge