services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: article_db
    ports:
      - 5432:5432  # Map the container's PostgreSQL port to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data using a named volume
    networks:
      - elt_bridge_network
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    networks:
      - elt_bridge_network

networks:
    elt_bridge_network:
      driver: bridge

volumes:
  postgres_data:  # Declare the named volume for persistent storage
