services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    hostname: mongo1
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    ports:
      - "27017:27017"
    networks:
      - elt_bridge_network
  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: mongo2
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    ports:
      - "27018:27017"
    networks:
      - elt_bridge_network
  mongo3:
    image: mongo:latest
    container_name: mongo3
    hostname: mongo3
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    ports:
      - "27019:27017"
    networks:
      - elt_bridge_network

networks:
  elt_bridge_network:
    driver: bridge
