FROM mongo:latest
# COPY replica_set.js /docker-entrypoint-initdb.d/
# COPY ./configdb/mongo-keyfile /data/configdb/mongo-keyfile
# RUN chmod 400 /data/configdb/mongo-keyfile && chown mongodb:mongodb /data/configdb/mongo-keyfile



