CREATE TABLE airbyte_data (
    id SERIAL PRIMARY KEY,
    oid TEXT,
    doi TEXT,
    core_id TEXT,
    oai TEXT,
    identifiers JSONB,
    title TEXT,
    authors JSONB,
    enrichments JSONB,
    contributors JSONB,
    date_published TEXT,
    abstract TEXT,
    download_url TEXT,
    raw_record_xml TEXT,
    journals JSONB,
    relations JSONB,
    year INTEGER,
    topics JSONB,
    subject JSONB,
    ab_source_file_last_modified TIMESTAMP,
    ab_source_file_url TEXT,
    airbyte_data_hash TEXT,
    airbyte_emitted_at TIMESTAMP
);