FROM ubuntu:latest

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends sudo ca-certificates curl


RUN echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER ubuntu
RUN curl -LsfS https://get.airbyte.com | bash -
# RUN sudo service docker start && sleep 10s
# RUN abctl local install
# RUN abctl local install --low-resource-mode --no-browser
# abctl local install --chart-version=1.3.0 --verbose
# ADD https://github.com/airbytehq/abctl/releases/download/v0.24.0/abctl-v0.24.0-linux-amd64.tar.gz abctl.tar.gz
# RUN tar -xvzf abctl.tar.gz -C .
# RUN chmod +x abctl*/abctl
# RUN sudo mv abctl /usr/local/bin
# RUN abctl local install --low-resource-mode
# RUN abctl local credentials
# -c', 'sudo docker run hello-world'
EXPOSE 8000

CMD ["tail", "-f", "/dev/null"]